In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score


# Importing the dataset
df = pd.read_csv('diabetes_csv.csv')
df.replace('?',-99999,inplace=True)
df.drop(['pedi'],1,inplace=True)

X=np.array(df.drop(['class'],1))
y=np.array(df['class'])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)
explained_variance=pca.explained_variance_ratio_


In [ ]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver="lbfgs")
lr.fit(X_train,y_train)
print("Test Accuracy: {}%".format(round(lr.score(X_test,y_test)*100,2)))

Test Accuracy: 70.13%


In [ ]:
# Fitting KNN to the Training set

from sklearn.neighbors import KNeighborsClassifier
knn = []
for i in range(21,42):
            
    classifier = KNeighborsClassifier(n_neighbors=i)
    trained_model=classifier.fit(X_train,y_train)
    trained_model.fit(X_train,y_train )
    
    # Predicting the Test set results
    
    y_pred = classifier.predict(X_test)
    
    # Making the Confusion Matrix
    
    from sklearn.metrics import confusion_matrix
    
    cm_KNN = confusion_matrix(y_test, y_pred)
    print(cm_KNN)
    print("Accuracy score of train KNN")
    print(accuracy_score(y_train, trained_model.predict(X_train))*100)
    
    print("Accuracy score of test KNN")
    print(accuracy_score(y_test, y_pred)*100)
    
    knn.append(accuracy_score(y_test, y_pred)*100)
    
plt.figure(figsize=(12, 6))  
plt.plot(range(21, 42),knn, color='red', linestyle='dashed', marker='o',  
             markerfacecolor='blue', markersize=10)
plt.title('Accuracy for different  K Value')  
plt.xlabel('K Value')  
plt.ylabel('Accuracy') 

[[40 10]
 [11 16]]
Accuracy score of train KNN
73.22720694645442
Accuracy score of test KNN
72.72727272727273
[[40 10]
 [14 13]]
Accuracy score of train KNN
73.22720694645442
Accuracy score of test KNN
68.83116883116884
[[39 11]
 [13 14]]
Accuracy score of train KNN
73.66136034732273
Accuracy score of test KNN
68.83116883116884
[[39 11]
 [14 13]]
Accuracy score of train KNN
73.22720694645442
Accuracy score of test KNN
67.53246753246754
[[39 11]
 [12 15]]
Accuracy score of train KNN
73.9507959479016
Accuracy score of test KNN
70.12987012987013
[[39 11]
 [12 15]]
Accuracy score of train KNN
73.66136034732273
Accuracy score of test KNN
70.12987012987013
[[38 12]
 [11 16]]
Accuracy score of train KNN
74.52966714905934
Accuracy score of test KNN
70.12987012987013
[[38 12]
 [12 15]]
Accuracy score of train KNN
74.09551374819102
Accuracy score of test KNN
68.83116883116884
[[38 12]
 [11 16]]
Accuracy score of train KNN
74.67438494934878
Accuracy score of test KNN
70.12987012987013
[[38 12]
 [

Text(0, 0.5, 'Accuracy')

In [ ]:
# Fitting SVM to the Training set

from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)

trained_model=classifier.fit(X_train,y_train)
trained_model.fit(X_train,y_train )


# Predicting the Test set results

y_pred = classifier.predict(X_test)

# Making the Confusion Matrix

from sklearn.metrics import confusion_matrix
cm_SVM = confusion_matrix(y_test, y_pred)
print(cm_SVM)
print("Accuracy score of train SVM")
print(accuracy_score(y_train, trained_model.predict(X_train))*100)

print("Accuracy score of test SVM")
print(accuracy_score(y_test, y_pred)*100)


[[43  7]
 [14 13]]
Accuracy score of train SVM
71.49059334298119
Accuracy score of test SVM
72.72727272727273


In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
print("Test Accuracy: {}%".format(round(dt.score(X_test,y_test)*100,2)))




Test Accuracy: 55.84%


In [ ]:
#Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,y_train)
print("Test Accuracy: {}%".format(round(nb.score(X_test,y_test)*100,2)))

Test Accuracy: 70.13%


In [ ]:
#Regression Classification
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver="lbfgs")
lr.fit(X_train,y_train)
print("Test Accuracy: {}%".format(round(lr.score(X_test,y_test)*100,2)))

Test Accuracy: 70.13%
